#############################################################################
# Makefile for building: imq
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  imq.pro
# Template: app
# Command: /Users/pro/Qt5-Source/current/bin/qmake -o Makefile imq.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../../Qt5-Source/current/mkspecs/macx-clang -I. -I../../../Qt5-Source/current/lib/QtNetwork.framework/Versions/5/Headers -I../../../Qt5-Source/current/lib/QtXml.framework/Versions/5/Headers -I../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers -I. -F/Users/pro/Qt5-Source/current/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Users/pro/Qt5-Source/current/lib -framework QtNetwork -framework QtCore -framework QtXml 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/pro/Qt5-Source/current/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		OsFile.cpp 
OBJECTS       = main.o \
		OsFile.o
DIST          = ../../../Qt5-Source/current/mkspecs/features/spec_pre.prf \
		../../../Qt5-Source/current/mkspecs/qdevice.pri \
		../../../Qt5-Source/current/mkspecs/features/device_config.prf \
		../../../Qt5-Source/current/mkspecs/common/shell-unix.conf \
		../../../Qt5-Source/current/mkspecs/common/unix.conf \
		../../../Qt5-Source/current/mkspecs/common/mac.conf \
		../../../Qt5-Source/current/mkspecs/common/macx.conf \
		../../../Qt5-Source/current/mkspecs/common/gcc-base.conf \
		../../../Qt5-Source/current/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5-Source/current/mkspecs/common/clang.conf \
		../../../Qt5-Source/current/mkspecs/common/clang-mac.conf \
		../../../Qt5-Source/current/mkspecs/qconfig.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5-Source/current/mkspecs/features/qt_functions.prf \
		../../../Qt5-Source/current/mkspecs/features/qt_config.prf \
		../../../Qt5-Source/current/mkspecs/macx-clang/qmake.conf \
		../../../Qt5-Source/current/mkspecs/features/spec_post.prf \
		../../../Qt5-Source/current/mkspecs/features/exclusive_builds.prf \
		../../../Qt5-Source/current/mkspecs/features/default_pre.prf \
		../../../Qt5-Source/current/mkspecs/features/mac/default_pre.prf \
		../../../Qt5-Source/current/mkspecs/features/resolve_config.prf \
		../../../Qt5-Source/current/mkspecs/features/default_post.prf \
		../../../Qt5-Source/current/mkspecs/features/mac/sdk.prf \
		../../../Qt5-Source/current/mkspecs/features/mac/default_post.prf \
		../../../Qt5-Source/current/mkspecs/features/mac/objective_c.prf \
		../../../Qt5-Source/current/mkspecs/features/warn_on.prf \
		../../../Qt5-Source/current/mkspecs/features/qt.prf \
		../../../Qt5-Source/current/mkspecs/features/resources.prf \
		../../../Qt5-Source/current/mkspecs/features/moc.prf \
		../../../Qt5-Source/current/mkspecs/features/unix/thread.prf \
		../../../Qt5-Source/current/mkspecs/features/mac/rez.prf \
		../../../Qt5-Source/current/mkspecs/features/testcase_targets.prf \
		../../../Qt5-Source/current/mkspecs/features/exceptions.prf \
		../../../Qt5-Source/current/mkspecs/features/yacc.prf \
		../../../Qt5-Source/current/mkspecs/features/lex.prf \
		imq.pro \
		imq.pro
QMAKE_TARGET  = imq
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = imq

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: imq.pro .qmake.cache ../../../Qt5-Source/current/mkspecs/macx-clang/qmake.conf ../../../Qt5-Source/current/mkspecs/features/spec_pre.prf \
		../../../Qt5-Source/current/mkspecs/qdevice.pri \
		../../../Qt5-Source/current/mkspecs/features/device_config.prf \
		../../../Qt5-Source/current/mkspecs/common/shell-unix.conf \
		../../../Qt5-Source/current/mkspecs/common/unix.conf \
		../../../Qt5-Source/current/mkspecs/common/mac.conf \
		../../../Qt5-Source/current/mkspecs/common/macx.conf \
		../../../Qt5-Source/current/mkspecs/common/gcc-base.conf \
		../../../Qt5-Source/current/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5-Source/current/mkspecs/common/clang.conf \
		../../../Qt5-Source/current/mkspecs/common/clang-mac.conf \
		../../../Qt5-Source/current/mkspecs/qconfig.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5-Source/current/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5-Source/current/mkspecs/features/qt_functions.prf \
		../../../Qt5-Source/current/mkspecs/features/qt_config.prf \
		../../../Qt5-Source/current/mkspecs/macx-clang/qmake.conf \
		../../../Qt5-Source/current/mkspecs/features/spec_post.prf \
		../../../Qt5-Source/current/mkspecs/features/exclusive_builds.prf \
		../../../Qt5-Source/current/mkspecs/features/default_pre.prf \
		../../../Qt5-Source/current/mkspecs/features/mac/default_pre.prf \
		../../../Qt5-Source/current/mkspecs/features/resolve_config.prf \
		../../../Qt5-Source/current/mkspecs/features/default_post.prf \
		../../../Qt5-Source/current/mkspecs/features/mac/sdk.prf \
		../../../Qt5-Source/current/mkspecs/features/mac/default_post.prf \
		../../../Qt5-Source/current/mkspecs/features/mac/objective_c.prf \
		../../../Qt5-Source/current/mkspecs/features/warn_on.prf \
		../../../Qt5-Source/current/mkspecs/features/qt.prf \
		../../../Qt5-Source/current/mkspecs/features/resources.prf \
		../../../Qt5-Source/current/mkspecs/features/moc.prf \
		../../../Qt5-Source/current/mkspecs/features/unix/thread.prf \
		../../../Qt5-Source/current/mkspecs/features/mac/rez.prf \
		../../../Qt5-Source/current/mkspecs/features/testcase_targets.prf \
		../../../Qt5-Source/current/mkspecs/features/exceptions.prf \
		../../../Qt5-Source/current/mkspecs/features/yacc.prf \
		../../../Qt5-Source/current/mkspecs/features/lex.prf \
		imq.pro \
		/Users/pro/Qt5-Source/current/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/pro/Qt5-Source/current/lib/QtCore.framework/QtCore.prl \
		/Users/pro/Qt5-Source/current/lib/QtXml.framework/QtXml.prl
	$(QMAKE) -o Makefile imq.pro
../../../Qt5-Source/current/mkspecs/features/spec_pre.prf:
../../../Qt5-Source/current/mkspecs/qdevice.pri:
../../../Qt5-Source/current/mkspecs/features/device_config.prf:
../../../Qt5-Source/current/mkspecs/common/shell-unix.conf:
../../../Qt5-Source/current/mkspecs/common/unix.conf:
../../../Qt5-Source/current/mkspecs/common/mac.conf:
../../../Qt5-Source/current/mkspecs/common/macx.conf:
../../../Qt5-Source/current/mkspecs/common/gcc-base.conf:
../../../Qt5-Source/current/mkspecs/common/gcc-base-mac.conf:
../../../Qt5-Source/current/mkspecs/common/clang.conf:
../../../Qt5-Source/current/mkspecs/common/clang-mac.conf:
../../../Qt5-Source/current/mkspecs/qconfig.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_core.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_designer.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_help.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_network.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_script.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5-Source/current/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt5-Source/current/mkspecs/features/qt_functions.prf:
../../../Qt5-Source/current/mkspecs/features/qt_config.prf:
../../../Qt5-Source/current/mkspecs/macx-clang/qmake.conf:
../../../Qt5-Source/current/mkspecs/features/spec_post.prf:
../../../Qt5-Source/current/mkspecs/features/exclusive_builds.prf:
../../../Qt5-Source/current/mkspecs/features/default_pre.prf:
../../../Qt5-Source/current/mkspecs/features/mac/default_pre.prf:
../../../Qt5-Source/current/mkspecs/features/resolve_config.prf:
../../../Qt5-Source/current/mkspecs/features/default_post.prf:
../../../Qt5-Source/current/mkspecs/features/mac/sdk.prf:
../../../Qt5-Source/current/mkspecs/features/mac/default_post.prf:
../../../Qt5-Source/current/mkspecs/features/mac/objective_c.prf:
../../../Qt5-Source/current/mkspecs/features/warn_on.prf:
../../../Qt5-Source/current/mkspecs/features/qt.prf:
../../../Qt5-Source/current/mkspecs/features/resources.prf:
../../../Qt5-Source/current/mkspecs/features/moc.prf:
../../../Qt5-Source/current/mkspecs/features/unix/thread.prf:
../../../Qt5-Source/current/mkspecs/features/mac/rez.prf:
../../../Qt5-Source/current/mkspecs/features/testcase_targets.prf:
../../../Qt5-Source/current/mkspecs/features/exceptions.prf:
../../../Qt5-Source/current/mkspecs/features/yacc.prf:
../../../Qt5-Source/current/mkspecs/features/lex.prf:
imq.pro:
/Users/pro/Qt5-Source/current/lib/QtNetwork.framework/QtNetwork.prl:
/Users/pro/Qt5-Source/current/lib/QtCore.framework/QtCore.prl:
/Users/pro/Qt5-Source/current/lib/QtXml.framework/QtXml.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile imq.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/imq1.0.0 || mkdir -p .tmp/imq1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/imq1.0.0/ && $(COPY_FILE) --parents OsFile.h .tmp/imq1.0.0/ && $(COPY_FILE) --parents main.cpp OsFile.cpp .tmp/imq1.0.0/ && (cd `dirname .tmp/imq1.0.0` && $(TAR) imq1.0.0.tar imq1.0.0 && $(COMPRESS) imq1.0.0.tar) && $(MOVE) `dirname .tmp/imq1.0.0`/imq1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/imq1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all: main.moc
compiler_moc_source_clean:
	-$(DEL_FILE) main.moc
main.moc: OsFile.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QCoreApplication \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcoreapplication.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QUrl \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qurl.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QDir \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qdir.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QDate \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		../../../Qt5-Source/current/lib/QtNetwork.framework/Versions/5/Headers/QNetworkAccessManager \
		../../../Qt5-Source/current/lib/QtNetwork.framework/Versions/5/Headers/qnetworkaccessmanager.h \
		../../../Qt5-Source/current/lib/QtNetwork.framework/Versions/5/Headers/QNetworkReply \
		../../../Qt5-Source/current/lib/QtNetwork.framework/Versions/5/Headers/qnetworkreply.h \
		../../../Qt5-Source/current/lib/QtNetwork.framework/Versions/5/Headers/QNetworkDiskCache \
		../../../Qt5-Source/current/lib/QtNetwork.framework/Versions/5/Headers/qnetworkdiskcache.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QMetaType \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmetatype.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QtCore \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qabstractanimation.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qanimationgroup.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qparallelanimationgroup.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qpauseanimation.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qpropertyanimation.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsequentialanimationgroup.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qvariantanimation.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtextcodec.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcompilerdetection.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qendian.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfeatures.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qflags.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qglobalstatic.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qisenum.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qlibraryinfo.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qnamespace.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qnumeric.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qprocessordetection.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsysinfo.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsystemdetection.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtypeinfo.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtypetraits.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qbuffer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qdatastream.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qdiriterator.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfiledevice.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfileselector.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfilesystemwatcher.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qiodevice.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qlockfile.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qloggingcategory.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qprocess.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qresource.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsavefile.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstandardpaths.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtemporarydir.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtemporaryfile.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qurlquery.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qabstractitemmodel.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qabstractproxymodel.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qidentityproxymodel.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qitemselectionmodel.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsortfilterproxymodel.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstringlistmodel.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qjsonarray.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qjsondocument.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qjsonobject.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qjsonvalue.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qabstracteventdispatcher.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qabstractnativeeventfilter.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qbasictimer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcoreevent.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qeventloop.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmath.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmetaobject.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmimedata.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qobjectcleanuphandler.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qobjectdefs.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qpointer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsharedmemory.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsignalmapper.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsocketnotifier.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsystemsemaphore.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtranslator.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qvariant.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qwineventnotifier.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmimedatabase.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmimetype.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfactoryinterface.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qlibrary.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qplugin.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qpluginloader.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/quuid.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qabstractstate.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qabstracttransition.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qeventtransition.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfinalstate.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qhistorystate.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsignaltransition.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstate.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstatemachine.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qatomic.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qexception.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfuture.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfutureinterface.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfuturesynchronizer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfuturewatcher.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qgenericatomic.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmutex.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qreadwritelock.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qresultstore.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qrunnable.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsemaphore.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qthreadpool.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qthreadstorage.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qwaitcondition.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qalgorithms.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qarraydata.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qarraydataops.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qarraydatapointer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qbitarray.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qbytearraymatcher.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qchar.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcollator.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcommandlineoption.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcommandlineparser.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcontainerfwd.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcontiguouscache.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcryptographichash.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qeasingcurve.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qelapsedtimer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qhash.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qiterator.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qline.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qlinkedlist.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qlocale.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmap.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmargins.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmessageauthenticationcode.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qpoint.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qqueue.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qrect.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qrefcount.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qregexp.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qregularexpression.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qscopedpointer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qscopedvaluerollback.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qset.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qshareddata.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsize.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstack.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstringbuilder.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstringmatcher.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtextboundaryfinder.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtimeline.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtimezone.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qvarlengtharray.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qxmlstream.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtcoreversion.h \
		main.cpp
	/Users/pro/Qt5-Source/current/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include/c++/4.2.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include/c++/4.2.1/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/5.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include main.cpp -o main.moc

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_source_clean 

####### Compile

main.o: main.cpp OsFile.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QCoreApplication \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcoreapplication.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QUrl \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qurl.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QDir \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qdir.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QDate \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		../../../Qt5-Source/current/lib/QtNetwork.framework/Versions/5/Headers/QNetworkAccessManager \
		../../../Qt5-Source/current/lib/QtNetwork.framework/Versions/5/Headers/qnetworkaccessmanager.h \
		../../../Qt5-Source/current/lib/QtNetwork.framework/Versions/5/Headers/QNetworkReply \
		../../../Qt5-Source/current/lib/QtNetwork.framework/Versions/5/Headers/qnetworkreply.h \
		../../../Qt5-Source/current/lib/QtNetwork.framework/Versions/5/Headers/QNetworkDiskCache \
		../../../Qt5-Source/current/lib/QtNetwork.framework/Versions/5/Headers/qnetworkdiskcache.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QMetaType \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmetatype.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QtCore \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qabstractanimation.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qanimationgroup.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qparallelanimationgroup.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qpauseanimation.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qpropertyanimation.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsequentialanimationgroup.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qvariantanimation.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtextcodec.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcompilerdetection.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qendian.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfeatures.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qflags.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qglobalstatic.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qisenum.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qlibraryinfo.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qnamespace.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qnumeric.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qprocessordetection.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsysinfo.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsystemdetection.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtypeinfo.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtypetraits.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qbuffer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qdatastream.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qdiriterator.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfiledevice.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfileselector.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfilesystemwatcher.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qiodevice.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qlockfile.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qloggingcategory.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qprocess.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qresource.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsavefile.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstandardpaths.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtemporarydir.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtemporaryfile.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qurlquery.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qabstractitemmodel.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qabstractproxymodel.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qidentityproxymodel.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qitemselectionmodel.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsortfilterproxymodel.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstringlistmodel.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qjsonarray.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qjsondocument.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qjsonobject.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qjsonvalue.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qabstracteventdispatcher.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qabstractnativeeventfilter.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qbasictimer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcoreevent.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qeventloop.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmath.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmetaobject.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmimedata.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qobjectcleanuphandler.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qobjectdefs.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qpointer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsharedmemory.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsignalmapper.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsocketnotifier.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsystemsemaphore.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtranslator.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qvariant.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qwineventnotifier.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmimedatabase.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmimetype.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfactoryinterface.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qlibrary.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qplugin.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qpluginloader.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/quuid.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qabstractstate.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qabstracttransition.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qeventtransition.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfinalstate.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qhistorystate.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsignaltransition.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstate.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstatemachine.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qatomic.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qexception.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfuture.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfutureinterface.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfuturesynchronizer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfuturewatcher.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qgenericatomic.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmutex.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qreadwritelock.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qresultstore.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qrunnable.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsemaphore.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qthreadpool.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qthreadstorage.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qwaitcondition.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qalgorithms.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qarraydata.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qarraydataops.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qarraydatapointer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qbitarray.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qbytearraymatcher.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qchar.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcollator.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcommandlineoption.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcommandlineparser.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcontainerfwd.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcontiguouscache.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcryptographichash.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qeasingcurve.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qelapsedtimer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qhash.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qiterator.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qline.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qlinkedlist.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qlocale.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmap.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmargins.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmessageauthenticationcode.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qpoint.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qqueue.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qrect.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qrefcount.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qregexp.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qregularexpression.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qscopedpointer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qscopedvaluerollback.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qset.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qshareddata.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsize.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstack.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstringbuilder.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstringmatcher.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtextboundaryfinder.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtimeline.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtimezone.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qvarlengtharray.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qxmlstream.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtcoreversion.h \
		main.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

OsFile.o: OsFile.cpp OsFile.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QCoreApplication \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcoreapplication.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QUrl \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qurl.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QDir \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qdir.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QDate \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		../../../Qt5-Source/current/lib/QtNetwork.framework/Versions/5/Headers/QNetworkAccessManager \
		../../../Qt5-Source/current/lib/QtNetwork.framework/Versions/5/Headers/qnetworkaccessmanager.h \
		../../../Qt5-Source/current/lib/QtNetwork.framework/Versions/5/Headers/QNetworkReply \
		../../../Qt5-Source/current/lib/QtNetwork.framework/Versions/5/Headers/qnetworkreply.h \
		../../../Qt5-Source/current/lib/QtNetwork.framework/Versions/5/Headers/QNetworkDiskCache \
		../../../Qt5-Source/current/lib/QtNetwork.framework/Versions/5/Headers/qnetworkdiskcache.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QMetaType \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmetatype.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QPair \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/QtCore \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qabstractanimation.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qanimationgroup.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qparallelanimationgroup.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qpauseanimation.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qpropertyanimation.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsequentialanimationgroup.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qvariantanimation.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtextcodec.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcompilerdetection.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qendian.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfeatures.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qflags.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qglobalstatic.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qisenum.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qlibraryinfo.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qnamespace.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qnumeric.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qprocessordetection.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsysinfo.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsystemdetection.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtypeinfo.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtypetraits.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qbuffer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qdatastream.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qdiriterator.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfiledevice.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfileselector.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfilesystemwatcher.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qiodevice.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qlockfile.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qloggingcategory.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qprocess.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qresource.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsavefile.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstandardpaths.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtemporarydir.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtemporaryfile.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qurlquery.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qabstractitemmodel.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qabstractproxymodel.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qidentityproxymodel.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qitemselectionmodel.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsortfilterproxymodel.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstringlistmodel.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qjsonarray.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qjsondocument.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qjsonobject.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qjsonvalue.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qabstracteventdispatcher.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qabstractnativeeventfilter.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qbasictimer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcoreevent.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qeventloop.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmath.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmetaobject.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmimedata.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qobjectcleanuphandler.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qobjectdefs.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qpointer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsharedmemory.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsignalmapper.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsocketnotifier.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsystemsemaphore.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtranslator.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qvariant.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qwineventnotifier.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmimedatabase.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmimetype.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfactoryinterface.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qlibrary.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qplugin.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qpluginloader.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/quuid.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qabstractstate.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qabstracttransition.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qeventtransition.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfinalstate.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qhistorystate.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsignaltransition.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstate.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstatemachine.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qatomic.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qexception.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfuture.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfutureinterface.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfuturesynchronizer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qfuturewatcher.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qgenericatomic.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmutex.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qreadwritelock.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qresultstore.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qrunnable.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsemaphore.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qthreadpool.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qthreadstorage.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qwaitcondition.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qalgorithms.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qarraydata.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qarraydataops.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qarraydatapointer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qbitarray.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qbytearraymatcher.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qchar.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcollator.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcommandlineoption.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcommandlineparser.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcontainerfwd.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcontiguouscache.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qcryptographichash.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qeasingcurve.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qelapsedtimer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qhash.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qiterator.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qline.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qlinkedlist.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qlocale.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmap.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmargins.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qmessageauthenticationcode.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qpoint.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qqueue.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qrect.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qrefcount.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qregexp.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qregularexpression.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qscopedpointer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qscopedvaluerollback.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qset.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qshareddata.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qsize.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstack.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstringbuilder.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qstringmatcher.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtextboundaryfinder.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtimeline.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtimezone.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qvarlengtharray.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qxmlstream.h \
		../../../Qt5-Source/current/lib/QtCore.framework/Versions/5/Headers/qtcoreversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OsFile.o OsFile.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/bin || mkdir -p $(INSTALL_ROOT)/usr/bin
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

